3537 infra decrease cluster config traffic
vostok/clusterconfig.core pull request #3
Opened 2021-12-03 07:58 UTC by anaym

2021-12-16 12:17 UTC, KungA requested changes

2021-12-16 12:17 UTC, kungasc commented on Vostok.ClusterConfig.Core/Serialization/TreeSerializerV2.cs
> +    internal class TreeSerializerV2 : ITreeSerializerV2
а зачем понадобился прямо новый сериалайзер, нельзя в старый просто добавить новый тип ноды?

2021-12-16 12:17 UTC, kungasc commented on Vostok.ClusterConfig.Core/Serialization/TreeSerializerV2.cs
> +        private static readonly UnboundedObjectPool<BinaryBufferWriter> WriterPool
выглядит странно, почему вдруг тут стали жить врайтеры

в V1 они снаружи давались

2021-12-16 12:17 UTC, kungasc commented on Vostok.ClusterConfig.Core/Serialization/TreeSerializerV2.cs
> +    //  + UTD-8 string
typo

2021-12-16 12:17 UTC, kungasc commented on Vostok.ClusterConfig.Core/Patching/DeleteNode.cs
> +        /// Creates a new <see cref="ValueNode"/> with the given <paramref name="name"/>.
typo

2021-12-16 12:17 UTC, KungA commented on Vostok.ClusterConfig.Core/Patching/Patcher.cs
> +        public ISettingsNode GetPatch([NotNull] ISettingsNode oldSettings, [NotNull] ISettingsNode newSettings)
странные ограничения на аргументы

почему допустимы не наллы?

кажется логичным сделать GetPatch(ObjectNode, null) => DeleteNode

а не где-то внутри `ISettingsNode GetPatch(ObjectNode oldObject, ObjectNode newObject)` этот случай обрабатывать

2021-12-16 12:17 UTC, KungA commented on Vostok.ClusterConfig.Core/Patching/Patcher.cs
> +            if (oldSettings is DeleteNode)
лучше явно разобрать подходящие нам случаи и в самом конце кинуть эксепшен когда ничего не подошло

2021-12-16 12:17 UTC, KungA commented on Vostok.ClusterConfig.Core/Patching/Patcher.cs
> +        public ISettingsNode ApplyPatch([NotNull] ISettingsNode oldSettings, [CanBeNull] ISettingsNode patch)
комментарии аналогичные к GetPatch

2021-12-16 12:33 UTC, KungA commented on Vostok.ClusterConfig.Core/Patching/Patcher.cs
> +                return GetReplacePatch(oldSettings, newSettings);
а тут не хотим если массив большой пытаться удалять из него некоторые ключи, а не целиком тащить?

2021-12-16 13:31 UTC, KungA requested changes

2021-12-16 13:31 UTC, KungA commented on Vostok.ClusterConfig.Core/Serialization/TreeSerializerV2.cs
> +    //  + pairs count (byte)
chilren count?

2021-12-16 13:31 UTC, KungA commented on Vostok.ClusterConfig.Core/Serialization/TreeSerializerV2.cs
> +    // ObjectNode content format:
а где name?

2021-12-16 13:31 UTC, KungA commented on Vostok.ClusterConfig.Core/Serialization/TreeSerializerV2.cs
> +    //    + Key (UTF-8 string)
давай просто писать string with|without length

вместо отдельно двух полей тут

2021-12-16 13:31 UTC, KungA commented on Vostok.ClusterConfig.Core/Serialization/TreeSerializerV2.cs
> +    //  + nodes
тут теперь можно не только Value ноды?

и что за тип у nodes не понятно (если Node[] то так и напиши)

2021-12-16 13:31 UTC, KungA commented on Vostok.ClusterConfig.Core/Serialization/TreeSerializerV2.cs
> +    //  + items count (byte)
почему вдруг byte?

2021-12-17 04:08 UTC, anaym commented on Vostok.ClusterConfig.Core/Serialization/TreeSerializerV2.cs
> +        private static readonly UnboundedObjectPool<BinaryBufferWriter> WriterPool
Вынес

2021-12-17 04:08 UTC, anaym commented on Vostok.ClusterConfig.Core/Serialization/TreeSerializerV2.cs
> +    //  + UTD-8 string
fix

2021-12-17 04:08 UTC, anaym commented on Vostok.ClusterConfig.Core/Patching/DeleteNode.cs
> +        /// Creates a new <see cref="ValueNode"/> with the given <paramref name="name"/>.
fix

2021-12-17 04:11 UTC, anaym commented on Vostok.ClusterConfig.Core/Patching/Patcher.cs
> +        public ISettingsNode GetPatch([NotNull] ISettingsNode oldSettings, [NotNull] ISettingsNode newSettings)
fix

2021-12-17 04:14 UTC, anaym commented on Vostok.ClusterConfig.Core/Patching/Patcher.cs
> +            if (oldSettings is DeleteNode)
Мы должны проверить что узел не DeleteNode до 
```
            if (oldSettings.GetType() != newSettings.GetType() || oldSettings.Name != newSettings.Name)
                return newSettings;
```
Иначе возможна ситуация когда нам на вход передали некорректные данные (мы не поддерживаем DeleteNode вне патча), а мы это обработали

2021-12-17 04:14 UTC, anaym commented on Vostok.ClusterConfig.Core/Patching/Patcher.cs
> +        public ISettingsNode ApplyPatch([NotNull] ISettingsNode oldSettings, [CanBeNull] ISettingsNode patch)
ответ аналогичный к GetPatch

2021-12-17 04:17 UTC, anaym commented on Vostok.ClusterConfig.Core/Patching/Patcher.cs
> +                return GetReplacePatch(oldSettings, newSettings);
Я думал об этом. Кажется что на данный момент это лишнее: [судя по тестам](https://github.com/vostok/clusterconfig.core/blob/master/Vostok.ClusterConfig.Core.Tests/Serialization/TreeSerializerV1_Tests.cs#L125) формат V1 не поддерживает ничего вложенного в массив, кроме ValueNode. Размер же одного файла (который может порождать массив) мы строго ограничиваем.

2021-12-17 04:18 UTC, anaym commented on Vostok.ClusterConfig.Core/Serialization/TreeSerializerV2.cs
> +    //  + pairs count (byte)
fix

2021-12-17 04:19 UTC, anaym commented on Vostok.ClusterConfig.Core/Serialization/TreeSerializerV2.cs
> +    // ObjectNode content format:
name хранится в ключе:
```
    //  + pairs, every pair:
    //    + Key length in bytes (int)
    //    + Key (UTF-8 string)
    //    + Value: any node
```
Т.е. корневой узел не может иметь имени, да. Но это ограничение [было и в формате V1](https://github.com/vostok/clusterconfig.core/blob/master/Vostok.ClusterConfig.Core/Serialization/TreeSerializerV1.cs#L21)

2021-12-17 04:22 UTC, anaym commented on Vostok.ClusterConfig.Core/Serialization/TreeSerializerV2.cs
> +    //    + Key (UTF-8 string)
fix

2021-12-17 04:23 UTC, anaym commented on Vostok.ClusterConfig.Core/Serialization/TreeSerializerV2.cs
> +    //  + nodes
Да, не только. Мне вообще не понятен семантический смысл данного ограничения в формате V1

2021-12-17 04:24 UTC, anaym commented on Vostok.ClusterConfig.Core/Serialization/TreeSerializerV2.cs
> +    //  + items count (byte)
fix

2021-12-17 10:27 UTC, KungA commented on Vostok.ClusterConfig.Core/Serialization/TreeSerializerV2.cs
> +        private static readonly UnboundedObjectPool<BinaryBufferWriter> WriterPool
что ты вынес, ты теперь их внутри создаешь)

почему бы не сохранить старый интерфейс просто?

2021-12-17 10:30 UTC, KungA commented on Vostok.ClusterConfig.Core/Patching/Patcher.cs
> +        public ISettingsNode GetPatch([NotNull] ISettingsNode oldSettings, [NotNull] ISettingsNode newSettings)
```
if (oldChild != null && newChild != null) diff = GetPatch(oldChild, newChild);
else if (oldChild != null) diff = new DeleteNode(key);
else if (newChild != null) diff = newChild;
```
а это зачем оставил?

2021-12-17 10:35 UTC, KungA commented on Vostok.ClusterConfig.Core/Patching/Patcher.cs
> +            if (oldSettings is DeleteNode)
тогда видимо и раньше проверок на налл надо передвинть

хотя у тебя и так может быть где-то в глубене дерева это самое DeleteNode

но я бы может вообще эти проверки выкинул, не понятно откуда тут могут эти DeleteNode попасть

2021-12-17 10:37 UTC, KungA commented on Vostok.ClusterConfig.Core/Patching/Patcher.cs
> +        public ISettingsNode ApplyPatch([NotNull] ISettingsNode oldSettings, [CanBeNull] ISettingsNode patch)
тут может много где тогда получается в результат случайно DeleteNode попасть

например ApplyPatch(null, DeleteNode) вроде как должен быть null

2021-12-17 10:40 UTC, KungA commented on Vostok.ClusterConfig.Core/Serialization/TreeSerializerV2.cs
> +    // (Children are ordered by key (OrdinalIgnoreCase))
это зачем появилось? всё равно бин-поиск не написать

2021-12-17 10:46 UTC, KungA commented on Vostok.ClusterConfig.Core/Serialization/TreeSerializerV2.cs
> +        private static readonly UnboundedObjectPool<BinaryBufferWriter> WriterPool
типо ITreeSerializerV1 и ITreeSerializerV2 не нужны

разве что ITreeSerializerV2 реализует ещё и ApplyPatch

но можно и вообще это не делать в интерфейсе сериалайзера

2021-12-17 10:51 UTC, KungA commented on Vostok.ClusterConfig.Core/Patching/Patcher.cs
> +        public ISettingsNode ApplyPatch([NotNull] ISettingsNode oldSettings, [CanBeNull] ISettingsNode patch)
стоит этот ApplyPatch сделать вообще идемпотентным

чтобы я мог накатить его лишний раз, и ничего не сломалось

2021-12-20 06:35 UTC, anaym commented on Vostok.ClusterConfig.Core/Serialization/TreeSerializerV2.cs
> +        private static readonly UnboundedObjectPool<BinaryBufferWriter> WriterPool
Мне важно чтобы на вход подавались BinaryBufferReader, чтобы я мог оперировать массивом байт внутри: чтобы быстро копировать массивы и следить за размером буфера. Поэтому не создавать **BinaryBufferReader** красиво не получится, либо нужно расширять интерфейс  IBinaryReader

2021-12-20 06:44 UTC, anaym commented on Vostok.ClusterConfig.Core/Patching/Patcher.cs
> +        public ISettingsNode GetPatch([NotNull] ISettingsNode oldSettings, [NotNull] ISettingsNode newSettings)
fix

2021-12-20 06:46 UTC, anaym commented on Vostok.ClusterConfig.Core/Serialization/TreeSerializerV2.cs
> +    // (Children are ordered by key (OrdinalIgnoreCase))
Для мёрджа двух ObjectNode на лету за линию, без необходимости вычитывать все ключи в хэшсет и считать по ним дифф

2021-12-20 06:53 UTC, KungA commented on Vostok.ClusterConfig.Core/Serialization/TreeSerializerV2.cs
> +        private static readonly UnboundedObjectPool<BinaryBufferWriter> WriterPool
чего, у тебя ITreeSerializerV2 наоборот байты принимать стал же?

2021-12-20 06:54 UTC, KungA commented on Vostok.ClusterConfig.Core/Serialization/TreeSerializerV2.cs
> +        private static readonly UnboundedObjectPool<BinaryBufferWriter> WriterPool
а в старом интерфейсе как раз IBinaryReader

2021-12-20 06:57 UTC, KungA commented on Vostok.ClusterConfig.Core/Serialization/TreeSerializerV2.cs
> +        private static readonly UnboundedObjectPool<BinaryBufferWriter> WriterPool
если вопрос в том, что в IBinaryReader чего-то не хватает, то лучше же туда и добавить это

2021-12-20 08:56 UTC, anaym commented on Vostok.ClusterConfig.Core/Patching/Patcher.cs
> +            if (oldSettings is DeleteNode)
убрал валидацию

2021-12-20 08:56 UTC, anaym commented on Vostok.ClusterConfig.Core/Patching/Patcher.cs
> +        public ISettingsNode ApplyPatch([NotNull] ISettingsNode oldSettings, [CanBeNull] ISettingsNode patch)
убрал валидацию

2021-12-20 09:22 UTC, anaym commented on Vostok.ClusterConfig.Core/Serialization/TreeSerializerV2.cs
> +        private static readonly UnboundedObjectPool<BinaryBufferWriter> WriterPool
fix

2021-12-20 10:11 UTC, KungA requested changes

2021-12-20 10:11 UTC, kungasc commented on Vostok.ClusterConfig.Core/Patching/Patcher.cs
> +            if (oldSettings.GetType() != newSettings.GetType() || oldSettings.Name != newSettings.Name)
compare names with IgnoreCase flag?

2021-12-20 10:11 UTC, kungasc commented on Vostok.ClusterConfig.Core/Patching/Patcher.cs
> +            throw new NotSupportedException($"Unknown node type {oldSettings.GetType().Name}");
имя ноды если есть тоже неплохо в эксепшен положить

2021-12-20 10:11 UTC, kungasc commented on Vostok.ClusterConfig.Core/Patching/Patcher.cs
> +            if (oldSettings.GetType() != patch.GetType() || oldSettings.Name != patch.Name)
compare names with IgnoreCase flag?

2021-12-20 10:11 UTC, kungasc commented on Vostok.ClusterConfig.Core/Patching/Patcher.cs
> +                return GetReplacePatch(oldSettings, newSettings);
inline GetReplacePatch

2021-12-20 10:11 UTC, kungasc commented on Vostok.ClusterConfig.Core/Patching/Patcher.cs
> +            if (oldSettings.GetType() != newSettings.GetType() || oldSettings.Name != newSettings.Name)
а вообще, как сюда могут попасть с разными именами ноды?

2021-12-20 10:11 UTC, kungasc commented on Vostok.ClusterConfig.Core/Patching/Patcher.cs
> +                .Where(diff => diff != null)
есть ощущение, что случай object[key] = null не эквивалентен случаю когда key нету в object

то есть если было

```
{
}
```

и стало

```
{
  "P": null
}
```

у нас вроде как получится DeleteNode

или наоборот (вроде тоже будет странное)

2021-12-20 10:11 UTC, kungasc commented on Vostok.ClusterConfig.Core/Patching/Patcher.cs
> +        #region GetPatch
в этом файле регионы только мешают читать код

2021-12-20 10:17 UTC, anaym commented on Vostok.ClusterConfig.Core/Patching/Patcher.cs
> +            if (oldSettings.GetType() != newSettings.GetType() || oldSettings.Name != newSettings.Name)
fix
В случае ClusterConfig-настроек - никак. В случае настроек создаваемых вручную - у корневого узла могу отличаться имена

2021-12-20 10:20 UTC, anaym commented on Vostok.ClusterConfig.Core/Patching/Patcher.cs
> +            throw new NotSupportedException($"Unknown node type {oldSettings.GetType().Name}");
fix

2021-12-20 10:20 UTC, anaym commented on Vostok.ClusterConfig.Core/Patching/Patcher.cs
> +            if (oldSettings.GetType() != patch.GetType() || oldSettings.Name != patch.Name)
fix

2021-12-20 10:21 UTC, anaym commented on Vostok.ClusterConfig.Core/Patching/Patcher.cs
> +                return GetReplacePatch(oldSettings, newSettings);
fix

2021-12-20 10:21 UTC, anaym commented on Vostok.ClusterConfig.Core/Patching/Patcher.cs
> +        #region GetPatch
fix

2021-12-20 12:14 UTC, kungasc requested changes

2021-12-20 12:14 UTC, kungasc commented on Vostok.ClusterConfig.Core/Patching/Patcher.cs
> +                .Distinct()
Comparers.NodeName

2021-12-20 12:14 UTC, kungasc commented on Vostok.ClusterConfig.Core/Patching/Patcher.cs
> +            var children = oldSettings.Children.ToDictionary(c => c.Name);
Comparers.NodeName

2021-12-20 12:14 UTC, kungasc commented on Vostok.ClusterConfig.Core/Patching/Patcher.cs
> +                var key = patchChild.Name ?? throw new InvalidOperationException("Key can't be null");
раз уж мы поняли, что null эквивалентно отсутствию child, то можно проще:

```suggestion
                var key = patchChild.Name ?? throw new InvalidOperationException("Key can't be null");
                var value = ApplyPatch(children[key], patchChild);
                if (value == null) children.Remove(key); else children[key] = value;
                
```

2021-12-20 12:14 UTC, kungasc commented on Vostok.ClusterConfig.Core/Serialization/TreeSerializerV2.cs
> +            if (patch.BytesRemaining == 0)
хотелось бы, чтобы всегда случаи разбирались в одинаковом порядке

например тут случай patch==null на первом месте, а в Patcher.ApplyPatch на втором

аналогично Patcher.GetPatch и Patcher.ApplyPatch

2021-12-20 12:14 UTC, kungasc commented on Vostok.ClusterConfig.Core/Serialization/V2/AnyNodeSerializerV2.cs
> +            objectSerializer = new ObjectNodeSerializerV2(this);
будет проще, если не делать разные сериалайзеры, а сделать один

можно оставить как сейчас в разных файлах (partial class)

всё будет норм работать благодаря разным типам (Serialize(ObjectNode), ObjectNode(ValueNode)...) или разным именам (DeserializeObject, DeserializeValue)

и не надо будет так сложно собирать DI

2021-12-20 12:14 UTC, kungasc commented on Vostok.ClusterConfig.Core/Serialization/V2/AnyNodeSerializerV2.cs
> +                case ObjectNode obj:
можно прямо тут сразу сделать

```
using (BeginNode(writer, GetNodeType(node))
```

аналогично упростится из Deserialize уберется EnsureType

и в самих методах останется только чтение/запись тела

2021-12-20 12:14 UTC, kungasc commented on Vostok.ClusterConfig.Core/Serialization/V2/AnyNodeSerializerV2.cs
> +            objectSerializer = new ObjectNodeSerializerV2(this);
да и методы
```
Deserialize(IBinaryReader reader, IEnumerator<string> path, string name)
public override void ApplyPatch(BinaryBufferReader settings, BinaryBufferReader patch, IBinaryWriter result)
```

нужны только для ObjectNode (если мы индексы не хотим сразу поддержать для массивов)

2021-12-20 12:14 UTC, kungasc commented on Vostok.ClusterConfig.Core/Serialization/V2/AnyNodeSerializerV2.cs
> +        public override ISettingsNode Deserialize(IBinaryReader reader, string name)
тут нельзя вызвать просто Deserialize c path = empty?

2021-12-20 12:14 UTC, kungasc commented on Vostok.ClusterConfig.Core/Serialization/V2/AnyNodeSerializerV2.cs
> +                    case NodeType.Array:
случаи Array/Value прямо тут лучше и разобрать

аналогично 

> хотелось бы, чтобы всегда случаи разбирались в одинаковом порядке

2021-12-20 12:14 UTC, kungasc commented on Vostok.ClusterConfig.Core/Serialization/V2/BaseSettingsNodeSerializerV2.cs
> +        protected void PeekHeader(IBinaryReader reader, out NodeType type, out int length)
это какой-то просто GetType, раз length не используется

и лучше сделать прямо экстеншены ReadType/WriteType на ридере/врайтере

возможно после резолва 

> и в самих методах останется только чтение/запись тела

можно будет вообще этот метод не сдвигающий указатель выкинуть

2021-12-20 12:14 UTC, KungA commented on Vostok.ClusterConfig.Core/Vostok.ClusterConfig.Core.csproj
> +    <Compile Include="..\..\vostok.commons.collections\Vostok.Commons.Collections\UnboundedObjectPool.cs">
не нужно оказалось же?

2021-12-20 12:14 UTC, kungasc commented on Vostok.ClusterConfig.Core/Utils/BinaryWriterExtensions.cs
> +        public static IntVariable AddIntVariable(this IBinaryWriter writer)
назови Reserve/Write

Add это как будто добавляем что-то

2021-12-20 12:14 UTC, kungasc commented on Vostok.ClusterConfig.Core/Serialization/V2/BaseSettingsNodeSerializerV2.cs
> +        protected enum NodeType : byte
вынести наружу

2021-12-20 12:14 UTC, kungasc commented on Vostok.ClusterConfig.Core/Utils/BinaryWriterExtensions.cs
> +        public static ContentLengthCounter AddContentLength(this IBinaryWriter writer)
бесполезный метод какой-то

2022-01-10 08:41 UTC, anaym commented on Vostok.ClusterConfig.Core/Utils/BinaryWriterExtensions.cs
> +        public static ContentLengthCounter AddContentLength(this IBinaryWriter writer)
Почему бесполезный? С помощью него удобно замерять длину контента

2022-01-10 08:42 UTC, KungA commented on Vostok.ClusterConfig.Core/Utils/BinaryWriterExtensions.cs
> +        public static ContentLengthCounter AddContentLength(this IBinaryWriter writer)
в методе 1 строчка, у метода 1 использование

не понятно почему не заинлайнить

2022-01-10 10:51 UTC, anaym commented on Vostok.ClusterConfig.Core/Utils/BinaryWriterExtensions.cs
> +        public static ContentLengthCounter AddContentLength(this IBinaryWriter writer)
Декомпозиция

2022-01-19 09:35 UTC, KungA approved these changes

2022-01-19 09:35 UTC, KungA commented on Vostok.ClusterConfig.Core/Serialization/V2/NodeReader.cs
> +        public NodeReader(BinaryBufferReader reader, Encoding encoding)
тут кажется нет смысла Encoding в конструктор тащить

2022-01-19 09:35 UTC, KungA commented on Vostok.ClusterConfig.Core/Vostok.ClusterConfig.Core.csproj
> +    <LangVersion>8</LangVersion>
это уже не нужно совсем вроде

https://github.com/vostok/clusterconfig.core/commit/ab9255d2fa27f891c0cc1b5ccba4e651afcd9dbf

2022-01-24 11:17 UTC, anaym commented on Vostok.ClusterConfig.Core/Vostok.ClusterConfig.Core.csproj
> +    <LangVersion>8</LangVersion>
Всё ещё нужно для паттернметчинга (как минимум)

2022-01-24 11:18 UTC, anaym commented on Vostok.ClusterConfig.Core/Serialization/V2/NodeReader.cs
> +        public NodeReader(BinaryBufferReader reader, Encoding encoding)
Почему? Гораздо логичнее когда кодировка задаётся снаружи, чем когда хардкодится внутри

2022-01-24 11:22 UTC, KungA commented on Vostok.ClusterConfig.Core/Serialization/V2/NodeReader.cs
> +        public NodeReader(BinaryBufferReader reader, Encoding encoding)
в итоге всегда ютф8, и в сериализаторе это не параметр, поэтому странно видеть два разных подхода по работе с одним и тем же

2022-01-24 11:36 UTC, anaym commented on Vostok.ClusterConfig.Core/Serialization/V2/NodeReader.cs
> +        public NodeReader(BinaryBufferReader reader, Encoding encoding)
Просто в сериализаторе это единственное место (хотя можно и в конструктор вынести, да), а в ридерах/врайтерах было бы два разных - при неосторожности можно поменять в одном, а во втором забыть.

Добавил конструктор

2022-01-24 11:37 UTC, KungA commented on Vostok.ClusterConfig.Core/Serialization/V2/NodeReader.cs
> +        public NodeReader(BinaryBufferReader reader, Encoding encoding)
можно и в константу просто вынести

2022-01-24 11:44 UTC, anaym commented on Vostok.ClusterConfig.Core/Serialization/V2/NodeReader.cs
> +        public NodeReader(BinaryBufferReader reader, Encoding encoding)
Можно, но лучше дать возможность менять

2022-01-25 06:45 UTC, merged